#!/bin/bash
port=$(cat $XDG_CONFIG_HOME/civtool/port)
opponent=$(cat $XDG_CONFIG_HOME/civtool/opponent)

# enable auto-pull
if ! (which nc &> /dev/null && [[ -n $opponent ]] && [[ -n $port ]])
then
	echo "[civpulld] couldn't start!"
	exit 1
fi

while true
do
	echo "[civpulld] listening for pull requests from $opponent on port $port..."
	response=$(nc -q 0 -vv -l -p $port)
	if [[ $? -eq 0 ]]
	then
		if [[ "$response" = "pull-request" ]]
		then
			echo "[civpulld] received a pull request, would be pulling..."
			#civ pull
		else
			echo "[civpulld] recieved something other than a valid request!"
		fi
	else
		echo "[civpulld] encountered an error!"
	fi
done
